### ISSUE TITLE
Rate Limits

### ISSUE THREAD

**Issue by godver3** [vysakh0/dravid#2]
Likely hitting rate limits trying to initialize an existing project:

(myenv) root@docker:~/ttrpg-combat-tracker# drd --i
ℹ Initializing project metadata...
ℹ Using .gitignore patterns for file exclusion.
ℹ The current folder structure:
ℹ ttrpg-combat-tracker/
    docker-compose.yml
    project.json
    Dockerfile
    package-lock.json
    package.json
    drd.json
    components/
        Libraries.js
        DiceRoller.module.css
        CombatTracker.js
        Layout.module.css
        Layout.js.save
        DiceRoller.js
        Layout.js
        CombatTracker.module.css
        Libraries.module.css
    styles/
        globals.css
        PlayerView.module.css
        Home.module.css
    pages/
        _app.js
        player-view.js
        index.js
        api/
            combatants.js
            test.js
    public/
        images/
            d4.png
            d8.png
            d10.png
            d6.png
            d2.png
            d20.png
            d100.png
            d12.png
    localStorage/
    src/
        styles/
            globals.css
        pages/
            index.tsx
    lib/
        combatants.js
✘ Error initializing project metadata: 429 Client Error: Too Many Requests for url: https://api.anthropic.com/v1/messages
✘ Stack trace:
Traceback (most recent call last):
  File "/root/myenv/lib/python3.11/site-packages/drd/metadata/initializer.py", line 82, in initialize_project_metadata
    file_type, description = generate_file_description(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/myenv/lib/python3.11/site-packages/drd/metadata/common_utils.py", line 87, in generate_file_description
    response = call_dravid_api_with_pagination(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/myenv/lib/python3.11/site-packages/drd/utils/api_utils.py", line 61, in call_dravid_api_with_pagination
    response = make_api_call(data, headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/myenv/lib/python3.11/site-packages/drd/utils/api_utils.py", line 35, in make_api_call
    response.raise_for_status()
  File "/root/myenv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.anthropic.com/v1/messages

**Comment by qria** [comment]
yeah anthropic's rate limit is very low unless you have staked a bunch of money there. I have like 400$ sitting there just for the rate limits.

**Comment by vysakh0** [comment]
@godver3 ah, makes sense. Will see if I can make a fix to workaround the rate limit, this happens when the folder has too many files.

**Comment by vysakh0** [comment]
@godver3 it is fixed in the latest release, please let me know 🎉
