### ISSUE TITLE
Cannot start --hf due to uvicorn error

### ISSUE THREAD

**Issue by ldorigo** [vysakh0/dravid#3]
```
ℹ Starting server monitor...
Starting server with command: uvicorn src.main:app --reload
ℹ Server monitor started. Press Ctrl+C to stop.
INFO:     Will watch for changes in these directories: ['/home/ldorigo/Dropbox/projects/pybooks/src/detectron2_server']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [135019] using StatReload
<frozen importlib._bootstrap>:488: UserWarning: enum class uv_fs_event not importable from uvloop.includes.uv. You are probably using a cpdef enum declared in a .pxd file that does not have a .py  or .pyx file.
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/usr/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run

```

Been playing with this, seems promising, but cannot start the auto-fixing mode.

**Comment by vysakh0** [comment]
@ldorigo Oh got it, I'll replicate this and update here.

**Comment by vysakh0** [comment]
<img width="1420" alt="Screenshot 2024-07-18 at 12 35 46 AM" src="https://github.com/user-attachments/assets/6c192f71-e674-4956-90c6-71e6f7396921">

<img width="1438" alt="Screenshot 2024-07-18 at 12 37 45 AM" src="https://github.com/user-attachments/assets/8e8e9949-25d6-4009-b4a4-cebde6afa695">

Couldn't exactly replicate the issue, is the command working fine without being part of the drd --hf command as a params? @ldorigo

**Comment by ldorigo** [comment]
Oh, so the uvicorn command is something drd is using to run _my_ project? I thought drd itself was using a uvicorn server for something internally. Then it makes sense that it doesn't work !
