### ISSUE TITLE
Add the option to confirm before executing commands

### ISSUE THREAD

**Issue by ldorigo** [vysakh0/dravid#4]
This is one of the most effective "auto-coders" I tried so far, but it's way too scary in its current state. It just zooms through commands at insane speed and I have no idea if at some points it decides that it needs to `rm -rf $HOME` and nuke all my data.

There should be a way to ask confirmation at each step (and even better, to provide input/edit the command because sometimes it goes on a tangent and the fix is obvious but there's no way to "tell it" to the AI.

**Comment by vysakh0** [comment]
Interesting pov.  I have added this checking the safe command thing that it will not run the command if it is any destructive command.
https://github.com/vysakh0/dravid/blob/main/src/drd/utils/step_executor.py#L16

```
def __init__(self):
        self.current_dir = os.getcwd()
        self.allowed_directories = [self.current_dir]
        self.disallowed_commands = [
            'rmdir', 'del', 'format', 'mkfs',
            'dd', 'fsck', 'mkswap', 'mount', 'umount',
            'sudo', 'su', 'chown', 'chmod'
        ]
        self.env = os.environ.copy()

    def is_safe_path(self, path):
        full_path = os.path.abspath(os.path.join(self.current_dir, path))
        return any(full_path.startswith(allowed_dir) for allowed_dir in self.allowed_directories)

    def is_safe_rm_command(self, command
```

Would you still feel it would be better if it asks for permissions especially when it runs the shell command even though something like this is there? @ldorigo

**Comment by vysakh0** [comment]
I was thinking about asking the user for permissions if any of the above destructive command is the shell command, if there is any other shell script like "source ~/.zshrc" or "wget ..." it would not ask permission, would that be good?

**Comment by ldorigo** [comment]
I think trying to blacklist any possible dangerous command is never going to be safe. E.g.:

```
echo "rm -rf /" > cmd.sh
bash cmd.sh
```

This  just defeated any blacklist protection you could have put :-) And since dravid is "self-healing" and can try to solve sub-problems, it's trivially easy for it to happen - tries `rm -rf /` first, sees it's blocked, then tries what I put above as a solution.

Don't think you need to make "ask for confirmation" obligatory, but it should be possible to enable with a flag.

**Comment by vysakh0** [comment]
@ldorigo Makes sense, you're right! I like this discussion, thanks for the input. Will make a change and update here.

**Comment by vysakh0** [comment]
@ldorigo done, changed it to have confirmation from the user before proceeding. Thanks for suggestion!
